# Generated by Django 3.2.4 on 2021-06-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_number', models.TextField()),
                ('address', models.TextField()),
                ('government_id', models.TextField()),
                ('e_mail', models.TextField()),
                ('no_of_rooms', models.IntegerField()),
                ('no_of_adults', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
            ],
        ),
    ]
