# Generated by Django 3.2.4 on 2021-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_rooms_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='discription',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='rooms',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='max_persons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='rate_for_extra_bed',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booked',
            name='address',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='booked',
            name='government_id',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booked',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booked',
            name='phone_number',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='no_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
