# Generated by Django 3.2.4 on 2021-06-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210625_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booked',
            name='government_id',
        ),
    ]
