# Generated by Django 3.2.4 on 2021-06-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20210626_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_photo_4',
            field=models.ImageField(default='media/about3.jpg', upload_to='rooms_image/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_photo_5',
            field=models.ImageField(default='media/about3.jpg', upload_to='rooms_image/'),
        ),
        migrations.AlterField(
            model_name='booked',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
